trim_isoseq_poly: main.cpp char_traits.hpp fasta.hpp format.hpp hmm_model.hpp matrix.hpp polyA_hmm_model.hpp sequence.hpp
	g++ -W -Wall -Wno-long-long -pedantic -Wno-variadic-macros -std=c++11 -I$(HOME)/.linuxbrew/include/ -L$(HOME)/.linuxbrew/lib/ main.cpp -static -lboost_iostreams -lboost_system -lboost_program_options -lz -lbz2  -o trim_isoseq_poly
